/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nationalteamplayer;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author fahru
 */
public class PlayerCard extends javax.swing.JPanel {
    
    private Player player;
    private DBConnection db;

    /**
     * Creates new form PlayerCard
     */
    public PlayerCard(Player player) {
        initComponents();
        
        // Connection
        db = new DBConnection();
        
        // Player
        this.player = new Player(
                player.getPlayerId(),
                player.getNationalTeamId(),
                player.getFoto(),
                player.getNama(),
                player.getNomorPunggung(),
                player.getPosisi()
        );
        
        // Display Card
        displayCard();
    }
    
    public void displayCard() {
        // Player Image
        Image image;
        try {
            image = ImageIO.read(new File(player.getFoto()));
            image = image.getScaledInstance(140, 142, Image.SCALE_SMOOTH);
            // Display Image
            imageLabel.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        
        // Get Data National Team
        ResultSet resTeam = db.selectQuery("SELECT * FROM national_team WHERE national_team_id ='" + player.getNationalTeamId() + "';");
        try {
            if (resTeam.next()) {
                teamValue.setText(resTeam.getString("negara"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        namaValue.setText(player.getNama());
        nomorValue.setText(String.valueOf(player.getNomorPunggung())); // Convert int to string
        posisiValue.setText(player.getPosisi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        nomorLabel = new javax.swing.JLabel();
        posisiLabel = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        nomorSeparator = new javax.swing.JLabel();
        namaSeparator = new javax.swing.JLabel();
        teamSeparator = new javax.swing.JLabel();
        posisiSeparator = new javax.swing.JLabel();
        teamValue = new javax.swing.JLabel();
        namaValue = new javax.swing.JLabel();
        nomorValue = new javax.swing.JLabel();
        posisiValue = new javax.swing.JLabel();

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        teamLabel.setText("National Team");

        namaLabel.setText("Nama");

        nomorLabel.setText("Nomor Punggung");

        posisiLabel.setText("Posisi");

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");

        btnUpdate.setBackground(new java.awt.Color(255, 204, 51));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");

        nomorSeparator.setText(":");

        namaSeparator.setText(":");

        teamSeparator.setText(":");

        posisiSeparator.setText(":");

        teamValue.setText("national_team");

        namaValue.setText("nama");

        nomorValue.setText("nomor_punggung");

        posisiValue.setText("posisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(teamLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teamSeparator))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomorLabel)
                                        .addComponent(namaLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaSeparator)
                                        .addComponent(nomorSeparator)
                                        .addComponent(posisiSeparator))))
                            .addComponent(posisiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomorValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(posisiValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teamLabel)
                            .addComponent(teamSeparator)
                            .addComponent(teamValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaLabel)
                            .addComponent(namaSeparator)
                            .addComponent(namaValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomorLabel)
                            .addComponent(nomorSeparator)
                            .addComponent(nomorValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posisiLabel)
                            .addComponent(posisiSeparator)
                            .addComponent(posisiValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>                            // Variables declaration - do not modify//GEN-END:initComponents
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaSeparator;
    private javax.swing.JLabel namaValue;
    private javax.swing.JLabel nomorLabel;
    private javax.swing.JLabel nomorSeparator;
    private javax.swing.JLabel nomorValue;
    private javax.swing.JLabel posisiLabel;
    private javax.swing.JLabel posisiSeparator;
    private javax.swing.JLabel posisiValue;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JLabel teamSeparator;
    private javax.swing.JLabel teamValue;
    // End of variables declaration//GEN-END:variables
}
